site:
  title: JOpedia
  start_page: summer::index.adoc
content:
  sources:
    - url: https://github.com/benjaminParisel/jo-summer
      start_path: docs
      branches: [2016, 2020, 2024]
    - url: https://github.com/tbouffard/jo-winter
      branches: [2018, 2022, 2026]

antora:
  extensions:
    - require: '@antora/lunr-extension'
# Asciidoctor extensions are commented to avoid errors when building the site offline for our Snowcamp talk
# asciidoc:
#   attributes:
#     kroki-fetch-diagram: true
#   extensions:
#     - asciidoctor-kroki

ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

urls:
  latest_version_segment: latest
  latest_prerelease_version_segment: next
  latest_version_segment_strategy: redirect:to
