site:
  title: JOpedia
  start_page: summer::index.adoc
content:
  sources:
    - url: https://github.com/benjaminParisel/jo-summer
      start_path: docs
      branches: [2016, 2020]
    - url: https://github.com/tbouffard/jo-winter
      branches: [2018, 2022]

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
